on: [ push, pull_request ]
jobs:
  unit_tests:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: "Setup CMake project"
        run: "cmake -B build/ -S . -DCMAKE_BUILD_TYPE=Debug -DTEST_ENABLE=yes -DCMAKE_CXX_FLAGS=\"-fsanitize=address -fno-sanitize-recover=all\""
      - name: "Build"
        run: "cmake --build build/ --parallel"
      - name: "Start"
        run: "./build/tests/libecs_tests"
