on: [ push, pull_request ]
jobs:
  unit_tests:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: "Install gcovr"
        run: "sudo apt-get install gcovr"
      - name: "Setup CMake project"
        run: "cmake -B build/ -S . -DCMAKE_BUILD_TYPE=Debug -DTEST_ENABLE=yes -DCOVERAGE_ENABLE=yes"
      - name: "Build"
        run: "cmake --build build/ --parallel"
      - name: "Start unit tests"
        run: "./build/tests/libecs_tests"
      - name: "Get coverage"
        run: "gcovr . --exclude build/ && gcovr . -b --exclude build/"
