on: [ push, pull_request ]
jobs:
  unit_tests:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: "Install valgrind"
        run: "sudo apt-get install valgrind"
      - name: "Setup CMake project"
        run: "cmake -B build/ -S . --config Debug -DTEST_ENABLE=yes"
      - name: "Build"
        run: "cmake --build build/ --parallel"
      - name: "Start unit tests"
        run: "valgrind --error-exitcode=1 --leak-check=full --leak-resolution=med --track-origins=yes --vgdb=no ./build/tests/libecs_tests"
