on: [ push, pull_request ]
jobs:
  unit_tests:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: "Setup CMake project"
        run: "cmake -B build/ -S . -DCMAKE_BUILD_TYPE=Release -DTEST_ENABLE=yes"
      - name: "Build"
        run: "cmake --build build/ --parallel"
      - name: "Start unit tests"
        run: "valgrind ./build/tests/libecs_tests.exe"